---
title: "EDA"
author: "Chen Liang (cl4469), Xinyi Shang (xs2529), Yuki Joyama (yj2803)"
date: "2024-03-20"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, message = F, warning = F)

library(tidyverse)
library(ggplot2)
library(corrplot)
library(gtsummary)
library(flextable)
library(RColorBrewer)
library(rsample) 
library(caret)
library(tidymodels)
library(plotmo)
library(earth)
library(vip)

# setup plot theme
theme_set(
  theme_bw() +
    theme(legend.position = "top")
  )
```


```{r dataprep}
# read RData file
df_recov <- get(load("./data/recovery.RData")) |> 
  janitor::clean_names()

summary(df_recov)
```

# Histogram
```{r}
cate_recov = df_recov |>
  select(gender, race, smoking, hypertension, diabetes, vaccine, severity, study)
conti_recov = df_recov |>
  select(age, height, weight, bmi, sbp, ldl, recovery_time)

#ggplot(gather(conti_recov, cols, value), aes(x = value)) + 
#       geom_histogram(binwidth = 20) + facet_grid(.~cols)

#library(Hmisc)
#hist.data.frame(conti_recov)

par(mfrow = c(2, 4),  # Layout: 2 rows, 4 columns
    oma = c(2, 2, 3, 1),  # Outer margins
    mar = c(4, 4, 2, 1),  # Inner margins
    mgp = c(2, 1, 0))     # Margins for labels and title

colors <- brewer.pal(8, "YlGnBu")

# Plot each histogram using a color from the Set3 palette
hist(conti_recov$age, main = "Age", xlab = "Year", ylab = "Frequency", col = colors[1])
hist(conti_recov$height, main = "Height", xlab = "cm", ylab = "Frequency", col = colors[2])
hist(conti_recov$weight, main = "Weight", xlab = "kg", ylab = "Frequency", col = colors[3])
hist(conti_recov$bmi, main = "BMI", xlab = " ", ylab = "Frequency", col = colors[4])
hist(conti_recov$sbp, main = "SBP", xlab = "mm/Hg", ylab = "Frequency", col = colors[5])
hist(conti_recov$ldl, main = "LDL", xlab = "mg/dL", ylab = "Frequency", col = colors[6])
hist(conti_recov$recovery_time, main = "Recovery Time", xlab = "Day", ylab = "Frequency", col = colors[7])

```


# Bar plot
```{r}
cate_recov = df_recov |>
  select(gender, race, smoking, hypertension, diabetes, vaccine, severity, study)
#ggplot(gather(cate_recov, cols, value), aes(x = value)) + 
#       geom_bar(binwidth = 20) + facet_grid(.~cols)

# Setting up the plotting area
par(mfrow = c(2, 4),  # Layout: 2 rows, 4 columns
    oma = c(2, 2, 3, 1),  # Outer margins
    mar = c(4, 4, 2, 1),  # Inner margins
    mgp = c(2, 1, 0))     # Margins for labels and title

barplot(table(cate_recov$gender), main = "Gender", ylab = "Count", , col = colors[1])
barplot(table(cate_recov$race), main = "Race", ylab = "Count", , col = colors[2])
barplot(table(cate_recov$smoking), main = "Smoking", ylab = "Count", col = colors[3])
barplot(table(cate_recov$hypertension), main = "Hypertension", ylab = "Count", col = colors[4])
barplot(table(cate_recov$diabetes), main = "Diabetes", ylab = "Count", col = colors[5])
barplot(table(cate_recov$vaccine), main = "Vaccine", ylab = "Count", col = colors[6])
barplot(table(cate_recov$severity), main = "Severity", ylab = "Count", col = colors[7])
barplot(table(cate_recov$study), main = "Study", ylab = "Count", col = colors[8])


```
```{r}
data_split = initial_split(df_recov, prop = .80)
train = training(data_split) |>
select( -id)
test = testing(data_split) |>
select( -id)

# Training data
x = model.matrix(recovery_time~.,train)[, -1]
y = train$recovery_time
# Testing data
x2 <- model.matrix(recovery_time~.,test)[, -1]
y2 <- test$recovery_time

featurePlot(x = x,  
            y = y,              
            plot = "scatter",
            auto.key = list(columns = 3)) 

```
```{r}
ggplot(data = df_recov, aes(x = study, y = recovery_time, fill = study)) +
  geom_boxplot() +
  labs(x = "Study Group", y = "Recovery Time",
       title = "Relationship Between Study Group and Recovery Time") +
  theme_minimal()
```

# Correlation
```{r}
numeric_df_recov <- df_recov |>
  mutate(race = as.numeric(race)) |>
  mutate(smoking = as.numeric(smoking)) |>
  mutate(study = as.numeric(as.factor(study))) |>
  select_if(is.numeric)


# Compute the correlation matrix
correlation_matrix <- cor(numeric_df_recov)

# Plot the correlation matrix
corrplot(correlation_matrix, method = "circle", type = "upper", order = "hclust")

```

# Table 1
```{r}
theme_gtsummary_journal(journal = "nejm")

table_1 = df_recov |> 
  select(!id) |> 
  mutate(
    gender = case_when(
      gender == 1 ~ "Male",
      gender == 0 ~ "Female"
    ),
    race = case_when(
      race == 1 ~ "White",
      race == 2 ~ "Asian",
      race == 3 ~ "Black",
      race == 4 ~ "Hispanic"
    ),
    smoking = case_when(
      smoking == 0 ~ "Never smoked",
      smoking == 1 ~ "Former smoker",
      smoking == 2 ~ "Current smoker"
    ), 
    hypertension = case_when(
      hypertension == 0 ~ "No hypertension",
      hypertension == 1 ~ "Hypertension"
    ),
    diabetes = case_when(
      diabetes == 0 ~ "No diabetes",
      diabetes == 1 ~ "Diabetes"
    ),
    vaccine = case_when(
      vaccine == 0 ~ "Not vaccinated",
      vaccine == 1 ~ "Vaccinated"
    ),
    severity = case_when(
      severity == 0 ~ "Not severe",
      severity == 1 ~ "Severe"
    )
  ) |> 
  tbl_summary(
    by = study,
    statistic = list(
      all_continuous() ~ "{mean} / {median} ({sd})",
      all_categorical() ~ "{n} ({p}%)"
    ),
    digits = all_continuous() ~ 1,
    label = list(
      age ~ "Age",
      gender ~ "Gender",
      race ~ "Race",
      smoking ~ "Smoking",
      height ~ "Height",
      weight ~ "Weight",
      bmi ~ "BMI",
      hypertension ~ "Hypertension",
      diabetes ~ "Diabetes",
      sbp ~ "SBP",
      ldl ~ "LDL",
      vaccine ~ "Vaccine",
      severity ~ "Severity",
      recovery_time ~ "Recovery time"
    )
  ) |> 
  # modify_caption("Table 1: Baseline Characteristics") |> 
  as_flex_table() |> 
  line_spacing(space = 0, part = "body")

table_1
```

